profiles:
  development:
  production:
    base_url: http://steamcannon.org
    deploy:
      host: steamcannon.org
      path: /var/www/domains/steamcannon.org/www/htdocs

intense_debate_acct: a9e7a0c66b1478d440fc1758c7a9ed0e
google_analytics: UA-6435340-3
